services:
  webhook:
    container_name: "webhook-site"
    image: "webhooksite/webhook.site"
    command: php artisan queue:work --daemon --tries=3 --timeout=10
    depends_on:
      - redis
    volumes:
      - webhook-sqlite:/app/database/data

  redis:
    container_name: "webhook-redis"
    image: "redis:alpine"

  laravel-echo-server:
    container_name: "laravel-echo-server"
    image: "webhooksite/laravel-echo-server"

volumes:
  webhook-sqlite:
