services:
  webhook:
    container_name: "webhook-site"
    image: "webhooksite/webhook.site:latest"
    command: php artisan queue:work --daemon --tries=3 --timeout=10
    depends_on:
      - redis
    volumes:
      - webhook-sqlite:/app/database/database.sqlite

  redis:
    container_name: "webhook-redis"
    image: "redis:alpine"
    volumes:
      - webhook-redis:/data

  laravel-echo-server:
    container_name: "laravel-echo-server"
    image: "webhooksite/laravel-echo-server"

volumes:
  webhook-sqlite:
  webhook-redis:
